### ISSUE TITLE
Links not being created

### ISSUE THREAD

**Issue by mjgangler** [method5/method5#61]
rror report -
ORA-20038: The SELECT statement did not run.
Please ensure the syntax is valid, all the objects exist, and you have access to all the objects.
Run this query to check your Method5 roles and privileges: select * from method5.m5_my_access_vw;
The statement was stopped after failing 100 times; use a more precise P_TARGETS if the SELECT only works on a small number of databases.
The SELECT statement raised this error:
ORA-06550: line 3, column 10:
PLS-00352: Unable to access another database 'M5_INGEPMPRD'
ORA-06550: line 3, column 10:
PLS-00201: identifier 'SYS@M5_INGEPMPRD' must be declared
ORA-06550: line 3, column 10:
PL/SQL: Statement ignored
ORA-06512: at "METHOD5.M5_PKG", line 2783
ORA-06512: at "METHOD5.M5_PKG", line 2838
ORA-06512: at "METHOD5.M5_PKG", line 3667
ORA-06512: at "METHOD5.M5_PROC", line 10
ORA-06512: at line 2

Note this database - INGEPMPRD is online and available from my source machine.

Also note - this error occurs when im trying to recreate the database links - 

begin
   m5_proc(p_code => 'select * from dual', p_asynchronous => false);
end;
=========

Ok, i removed this database from Method5 and tried to rerun - and it failed on the next database was INGEPMQA.  Both databases were coincidentally the 100th database in the table.

Is the 100th row / database in the table the source of the issue and if so why ?

**Comment by jonheller1** [comment]
Michael,

The 100 limit only applies to the number of errors.  So that error message implies that the statement is failing for *all* databases, and INGEPMPRD and INGEPMQA just happen to be the 100th database.

Does it really fail with `select * from dual`, or is the real SQL statement different?  Does Method5 work for any of your databases or did it suddenly stop working for all of them?

Also, what version are you using?  You can find it with this statement:
```
set serveroutput on;
begin
	dbms_output.put_line(method5.m5_pkg.c_version);
end;
/
```

Thanks,
Jon

**Comment by mjgangler** [comment]
Im confused - I fixed the duplicate database names - and ran the create links and got (BTW - INGEPMPRD is the 100th row)

Version - 9.2.4

Error starting at line : 1 in command -
begin
   m5_proc(p_code => 'select * from dual', p_asynchronous => false);
end;
Error report -
ORA-20038: The SELECT statement did not run.
Please ensure the syntax is valid, all the objects exist, and you have access to all the objects.
Run this query to check your Method5 roles and privileges: select * from method5.m5_my_access_vw;
The statement was stopped after failing 100 times; use a more precise P_TARGETS if the SELECT only works on a small number of databases.
The SELECT statement raised this error:
ORA-06550: line 3, column 10:
PLS-00352: Unable to access another database 'M5_INGEPMPRD'
ORA-06550: line 3, column 10:
PLS-00201: identifier 'SYS@M5_INGEPMPRD' must be declared
ORA-06550: line 3, column 10:
PL/SQL: Statement ignored
ORA-06512: at "METHOD5.M5_PKG", line 2783
ORA-06512: at "METHOD5.M5_PKG", line 2838
ORA-06512: at "METHOD5.M5_PKG", line 3667
ORA-06512: at "METHOD5.M5_PROC", line 10
ORA-06512: at line 2

Select * from table(m5(‘select * from dual’))

ORA-20003: Error executing or dropping method5.m5_temp_procedure_151645.  Investigate that procedure and drop it when done.
ORA-02011: duplicate database link name
ORA-06512: at "METHOD5.M5_TEMP_PROCEDURE_151645", line 3
ORA-06512: at line 1
ORA-06512: at "METHOD5.M5_PKG", line 1714
ORA-06512: at "METHOD5.M5_PKG", line 1724
ORA-06512: at "METHOD5.M5_PKG", line 3660
ORA-06512: at "METHOD5.METHOD4_M5_POLL_TABLE_OT", line 236
ORA-06512: at line 4


create or replace procedure         m5_temp_procedure_151645 is
				begin
					execute immediate q'!
						create database link M5_ADLUK
						connect to method5
						identified by not_a_real_password_yet
						using '(description=(address=(protocol=tcp)(host=agii-orapl05)(port=1528))(connect_data=(service_name=adluk))) '
					!';
				end;

I dropped the links and tried again - same errors.

—Mike

**Comment by jonheller1** [comment]
@mjgangler 

I'm guessing this is a GLOBAL_NAMES or DB_DOMAIN issue.  Is there some link with a slightly similar name, that's causing the "duplicate"?

Does this query return anything weird?

	select owner, db_link from dba_db_links where db_link like '%M5_ADLUK%';

I don't suppose you've changed GLOBAL_NAMES or DB_DOMAIN recently?  Method5 creates missing links based on M5_DATABASE, even if that link isn't related to your query.  Take a look at M5_DATABASE, and look for new entries, maybe ones with weird names?

There have been a few small changes to the DB_DOMAIN logic since 9.2.4.  (Although if these problems didn't occur for you before, I'm not sure why they would occur now.)  Upgrading might help.

These problems can be tough to diagnose.  If you'd like, we can setup a WebEx tomorrow and I can take a look at your system.  You can email me at jon@jonheller.org or call me at 919-333-6378 if you want to setup a WebEx meeting.

Thanks,
Jon

**Comment by jonheller1** [comment]
Per our last email this was resolved with the latest version.  But let me know if there are still some problems.
